### PR TITLE
add kgn algorithm

### PR DESCRIPTION
**Pull request by Henry-yan**
add kgn algorithm

### CODE REVIEW

**Comment by maumueller** [comment]
Hi @Henry-yan! Thanks for your contribution: Could you link to your repo in the README.md and maybe add a bit information (is there a paper?) Are you planning to open-source your contribution?

**Comment by Henry-yan** [comment]
> Hi @Henry-yan! Thanks for your contribution: Could you link to your repo in the README.md and maybe add a bit information (is there a paper?) Are you planning to open-source your contribution?↳

Thank you for your suggestion, we have updated the README.md with the repository link. We currently do not have plans to open source.

**Comment by Henry-yan** [comment]
Hello @maumueller, would you please consider merge this PR? Since there are already a lot of close-source algorithm in this repo, they should be fairly treated.

**Comment by Henry-yan** [comment]
Hello @maumueller @erikbern , we plan to submit a paper, and upon its acceptance, we intend to open-source our algorithm. Could you please consider merging our pull request first? It would be greatly appreciated.

**Comment by maumueller** [comment]
Alright, I'm merging this for now.

**Pull request merged**
