### PR TITLE
add n2

### PR DESCRIPTION
**Pull request by taesaza0**
Sorry, we are late 🙏. We released the minor update and want to add it by changing the N2 configuration.
(Not yet major update, It seems to take longer than expected)

related issue: https://github.com/erikbern/ann-benchmarks/issues/130
related pr: https://github.com/erikbern/ann-benchmarks/pull/147

### CODE REVIEW

**Comment by erikbern** [comment]
nice thanks!

**Comment by erikbern** [comment]
i can kick off a new benchmark later this week – think it's overdue

**Comment by taesaza0** [comment]
@erikbern 
I understand that there is only one cpu in the benchmark, but I wonder if it's the same in the build phase(ex, hnsw build)
We explicitly set the number of threads to one for build and search phase, is it the right way?

**Comment by erikbern** [comment]
it's possible we can use multiple cpus for the build phase, but i think it's fine that it's a bit slower than it could be

**Pull request merged**
