### PR TITLE
New results

### PR DESCRIPTION
**Pull request by erikbern**
See new plots

### CODE REVIEW

**Comment by erikbern** [comment]
Will add a couple more datasets to this shortly!

**Comment by thomasahle** [comment]
Oh no, looks like fast_pq/tinyknn regressed substantially since https://github.com/erikbern/ann-benchmarks/issues/363#issuecomment-1510390881 and is completely broken on mnist.
Are these new runs final? Or do we still have time to fix bugs?

**Comment by thomasahle** [comment]
Is the run actually using the latest ann-benchmarks code? It seems the string fast_pq should have been replaced in the repo

**Comment by erikbern** [comment]
> Is the run actually using the latest ann-benchmarks code? It seems the string fast_pq should have been replaced in the repo

I just realize I haven't re-run install.py in the last few days. Let me wipe the fast_pq data and re-run all benchmarks (will also wipe opensearchknn)

**Comment by thomasahle** [comment]
> > Oh no, looks like fast_pq/tinyknn regressed substantially since [#363 (comment)](https://github.com/erikbern/ann-benchmarks/issues/363#issuecomment-1510390881) and is completely broken on mnist.
> > Are these new runs final? Or do we still have time to fix bugs?
> 
> If you fix it in the next few hours, then I can re-run it. But I want to tear down the r6.16xlarge instance soon (it's ~$100/day)

I found the problem. Just testing my fix now. Will push it asap.

**Comment by thomasahle** [comment]
It's pushed.

**Comment by WPJiang** [comment]
> Pushed latest results. Going to run gist-960-euclidean as well just to have a high dimensional dataset that's a bit larger. It will probably take 10h.

hi，@erikbern there is only one line -tinyknn in the new result of glove25, would you please check it?

**Comment by erikbern** [comment]
> hi，@erikbern there is only one line -tinyknn in the new result of glove25, would you please check it?

You're right, I accidentally ran glove-25 only for tinyknn. Let me run it for all algos.

**Comment by thomasahle** [comment]
It's strange. This is what I get when I spin up an r6i.8xlarge myself and run tinyknn on sift. Maybe I pushed the update too late, after you had already rerun install.py? Or maybe there's some other issue I can't think of...
sift-128-euclidean

**Comment by erikbern** [comment]
It's possible the image didn't rebuild because of Docker layer caching. I didn't check closely. I'll rerun soon though.

**Comment by thomasahle** [comment]
If the docker image times out during querying, is the data gathered still saved? Or is saving the data part of the job being run inside the docker container, so it gets lost? In the later case I can try to reduce the number of query_args to prevent timeouts.
It seems to me that the build-args/groups each have their own 7200s timeout, so I reducing them probably won't make a difference?

**Comment by erikbern** [comment]
the process running inside the container saves the data to data that's mounted into the container from the outside – so if the container is killed after 2h, any data saved up to that point is kept

generally the 2h timeout happens during index building though, not afterwards during query processing. that step is usually pretty fast.

**Comment by WPJiang** [comment]
> It's possible the image didn't rebuild because of Docker layer caching. I didn't check closely. I'll rerun soon though.
I think  this 
        for query_arguments in query_argument_groups:
            fn = get_result_filename(args.dataset, args.count, definition, query_arguments, args.batch)
            if args.force or not os.path.exists(fn):
                not_yet_run.append(query_arguments)

**Comment by thomasahle** [comment]
> generally the 2h timeout happens during index building though

It seems some of the last args were taking more than half an hour, so I trimmed the list down. Now none of the rounds should take more than a minute or two.
https://github.com/erikbern/ann-benchmarks/pull/406

**Comment by erikbern** [comment]
Merging this for now, but I'm planning to run this again in just a week or two. Will also polish the graphs a bit. But I don't want perfection to get in the way of getting something updated out. Won't promote this for now.

**Pull request merged**
