### PR TITLE
Upgrade to use newer NMSLIB api

### PR DESCRIPTION
**Pull request by benfred**
Nice work on all the recent changes! I saw your post this morning and decided play around with this again.

One thing I noticed was that this package is using an old version of the nmslib api. While I kept that version around for backwards compatibility, the newer version has a couple of advantages: you don't
need to call freeIndex, the newer version accepts numpy arrays as inputs etc etc.

Also, I think you are running into this issue https://github.com/searchivarius/nmslib/issues/291 . I noticed that the tests hung here, but when switching the Dockerfile.nmslib to point to my repo of nmslib (with the fix) it worked.

### CODE REVIEW

**Comment by erikbern** [comment]
cool thanks, will merge if this builds!

**Comment by erikbern** [comment]
btw fun to see a PR from you – have been following your blog for a while and seems like you're working on some fun stuff. I know at least one person have confused the two of us due to similar names :)

**Comment by benfred** [comment]
Thanks! I've been following your blog for a while too =).

I think the build won't work until that issue in nmslib is merged. It looks like the build is hanging on the deadlock in pybind11. I'll restart the CI here once the fix is merged into master in nmslib.

**Comment by erikbern** [comment]
got it, thanks

**Comment by erikbern** [comment]
thanks!

**Pull request merged**
