### PR TITLE
Update PyNNDescent

### PR DESCRIPTION
**Pull request by lmcinnes**
I recently released a new version of pynndescent. This should get ann-benchmarks working with it. There are a couple of other changes from issues encountered with my own testing. First the addition of ``freeze_support`` to make things play nice with newer multiprocessing releases, and second a minor change to the ScaNN model so that it will at least run on NYTimes (the all zero vectors in that dataset were breaking it).

### CODE REVIEW

**Comment by erikbern** [comment]
thanks! just checking, the amount of runs is still reasonable right? i don't want the benchmark suite to blow up :)

**Comment by lmcinnes** [comment]
It is actually less runs; just broken up differently, so it expands out in the algos.yaml.

Right now I'm fighting with some issues of Docker (I run things with --local for testing). Hopefully I'll get those sorted soon.

**Comment by lmcinnes** [comment]
Out of curiousity, does the jaccard benchmark get run at all? I have been trying to maintain the code to make it work, but I've never seen benchmarks posted for Kosarak, so I'm wondering if it is worthwhile.

**Comment by erikbern** [comment]
I haven't looked at Jaccard – it was something @maumueller built. I can try to run it next time and see how many algorithms support it.

**Comment by lmcinnes** [comment]
Looks like it is just faiss and milvus now, which I don't believe I touched. Thanks again for taking the time to build all of this. It has been invaluable for me to have a consistent way to do my own benchmarking, and it provides a great service to the community on the current state-of-the-art.

**Comment by lmcinnes** [comment]
It seems like milvus just has a stale link for a config file (although the version also seems very out of date; it is 0.6.0, but they seem to be on 0.10.2 now). I'm not sure where to get the right one though. Faiss seems to be due to the fact that they have moved from autotools to cmake for build configuration. Ideally that isn't too hard to fix but they seem to have a lot of carefully crafted flags in their install file, so I wouldn't really want to mess with that. I don't believe I can fix either of those, so this is about as good a state as this PR is ever going to be in I'm afraid.

**Comment by erikbern** [comment]
No worries, not your job to fix those other algorithms!

**Comment by stephenleo** [comment]
Can we merge this in? build is still failing at pynndescent. At least one of the issue is with the renaming of a parameter `diversify_epsilon` to `diversify_prob` which this PR seems to fix.

If you need some help to test it on Debian, Ubuntu, etc let me know. I can run it on a fresh GCP VM.

**Comment by erikbern** [comment]
looks like this one is now going to have to be rebased :/

**Comment by lmcinnes** [comment]
Conflicts should be resolved now.

**Comment by erikbern** [comment]
@lmcinnes I just ran this locally but it's failing at the last step:

```
Step 7/7 : RUN python3 -c 'import pynndescent'
 ---> Running in ecc021cc872b
double free or corruption (top)
Aborted
The command '/bin/sh -c python3 -c 'import pynndescent'' returned a non-zero code: 134
```

**Comment by erikbern** [comment]
Thanks @lmcinnes !

**Comment by erikbern** [comment]
Unfortunately it's failing after merging:

```
Step 7/7 : RUN python3 -c 'import pynndescent'
 ---> Running in eb006d9d49ec
double free or corruption (top)
Aborted
The command '/bin/sh -c python3 -c 'import pynndescent'' returned a non-zero code: 134
```

**Comment by erikbern** [comment]
Fix in #198

**Pull request merged**
