### PR TITLE
Add glass

### PR DESCRIPTION
**Pull request by hhy3**
add glass

### CODE REVIEW

**Comment by hhy3** [comment]
@erikbern It's open-sourced now. Could you please take a look

**Comment by hhy3** [comment]
@erikbern Could you please let me know if this will be merged in? Thanks!

**Comment by erikbern** [comment]
Afaict it's still just installing a wheel? (from PyPI this time, instead of Github).

**Comment by hhy3** [comment]
> Afaict it's still just installing a wheel? (from PyPI this time, instead of Github).

It's the same as building from the source. I will change it to build from source if you insist :)

**Comment by erikbern** [comment]
Can you put the source code on Github? Ideally in a way where it can clone the repo and build the library from source. But pip install from pypi is fine too assuming the code is open source.

I think ann-benchmarks should contain algorithms that are usable for people running ANN in production. So that means that they can trust the source code, ideally that there's good documentation, issue tracking, etc.

**Comment by hhy3** [comment]
> Can you put the source code on Github? Ideally in a way where it can clone the repo and build the library from source. But pip install from pypi is fine too assuming the code is open source.
> 
> I think ann-benchmarks should contain algorithms that are usable for people running ANN in production. So that means that they can trust the source code, ideally that there's good documentation, issue tracking, etc.

Sure. It is now open-sourced at https://github.com/hhy3/pyglass, with a simple README.md and you can try it yourself. But the build system is not mature and sometimes causes compiling errors. So it's recommended to install using pip with pre-built binaries. I'm writing the documents now.

**Comment by erikbern** [comment]
Nice – looks good!

**Comment by handsomeZhuang** [comment]
> build system is not mature and sometimes causes compiling errors with a different compiler. So it's recommended to ins

hi，could you run glass and output the ann-benchmarks‘ performance? if ok, could you share your source code?

**Pull request merged**
