### PR TITLE
Updated kgraph parameters and etc

### PR DESCRIPTION
**Pull request by aaalgo**
- A command line argument "--algo" is added so one can run only one algorithm instead of all.
- Updated kgraph configuration for two dataset separately.

sift
glove

### CODE REVIEW

**Comment by erikbern** [comment]
nice! i will re-run all algorithms shortly!

**Comment by searchivarius** [comment]
@erikbern would you wait a few days? :-) we will make some minor updates.

**Comment by erikbern** [comment]
yeah just lmk when you are done. maybe the upcoming weekend

**Comment by searchivarius** [comment]
Ok, thanks! I will also update the code so that it is possible to run with and without saving indices. Saving will be set by default b/c I can see no serious reason to disable it, but you will be able to do it if you wish.

**Comment by erikbern** [comment]
ok sounds good

**Comment by erikbern** [comment]
i'm rerunning the benchmarks but kgraph keeps crashing

the last thing it outputs is `Graph completion with reverse edges...`

**Comment by searchivarius** [comment]
@erikbern I am doing the same now (before submitting a pull request), and I see the same thing. It works on sift (greatly) but crashes on glove.

**Comment by erikbern** [comment]
ok weird. btw i've changed the setup a bit and the results are slightly different. see https://github.com/erikbern/ann-benchmarks/pull/28

**Comment by searchivarius** [comment]
@erikbern I thought Python had no real threads (at least not 2.x). But, can FLANN use threads internally, inside the library?

**Comment by searchivarius** [comment]
PS: by internally, I mean intra-query parallelism.

**Comment by erikbern** [comment]
Python has real threads but also the global interpreter lock. But if you use threads inside a library, there's no locking

**Comment by searchivarius** [comment]
@erikbern that's right, you can run a multi-threaded test in Python only if a library somehow supports multi-threading inside it. For example, it can have intra-query parallelism or it has its own thread pool. To make use of the thread pool, there should be some support for batch-query submission. I don't think most libraries support this. I also think that FALCONN isn't thread safe (though it uses multi-threading for index creation).

**Comment by searchivarius** [comment]
Intra-query || is possible, but it's much easier to have separate threads each processing the complete request (unless you need to reduce latency).

**Comment by aaalgo** [comment]
I'm looking into the problem right now.  Will report shortly.

**Comment by aaalgo** [comment]
I ran out of memory.  I've updated KGraph.   Even though memory is still tight, the benchmark is working now on my c4.2xlarge instance.

**Comment by searchivarius** [comment]
Nice, thanks. I am going to submit a pull request within several hours. The performance is nearly the same, but it has a flag to enable/disable saving of indices + a bit of refactoring to reduce the clutter.

**Pull request merged**
