### PR TITLE
qdrant implementation

### PR DESCRIPTION
**Pull request by raulcarlomagno**

### CODE REVIEW

**Comment by erikbern** [comment]
Nice! happy to merge this when you're ready

**Comment by raulcarlomagno** [comment]
hi @erikbern , could you re run checks? it should work

**Comment by erikbern** [comment]
Thanks for the contribution @raulcarlomagno !

**Comment by raulcarlomagno** [comment]
you are welcome @erikbern 
what's next to see qdrant's results on the main page?

**Comment by erikbern** [comment]
I will have to rerun the benchmarks. It's been a while since last time so I can try to do it in the next couple of months!

**Pull request merged**
