### PR TITLE
Update qsgngt from 3.0.0 to 4.0.0

### PR DESCRIPTION
**Pull request by SDU-L**

### CODE REVIEW

**Comment by erikbern** [comment]
nice! is this ready to be merged?

**Comment by WPJiang** [comment]
> nice! is this ready to be merged?

@erikbern yes，it is ready to be merged, and when will you rerun the benchmarks? Looking forward to your reply, thank you very much

**Comment by erikbern** [comment]
Thanks! Hoping to run it in the next few weeks. Sorry I'm behind on a lot of things :(

**Comment by erikbern** [comment]
I'm having occasional issues installing qsgngt. See https://github.com/erikbern/ann-benchmarks/actions/runs/4639331199/jobs/8210066339

```
 Cloning into 'hwtl_sdu-anns-qsgngtlib'...
fatal: unable to access 'https://gitee.com/WPJIANG-gitee/hwtl_sdu-anns-qsgngtlib.git/': Empty reply from server
```

Maybe move it to Github?

**Pull request merged**
