### PR TITLE
Added FastPQ

### PR DESCRIPTION
**Pull request by thomasahle**
Adds https://github.com/thomasahle/fast_pq to AnnBenchmarks

### CODE REVIEW

**Comment by erikbern** [comment]
let me know when this is ready to be merged!

**Comment by thomasahle** [comment]
@erikbern What is actually right command to test run?
```
py run.py --docker-tag ann-benchmarks-fast_pq --max-n-algorithms 3 --runs 2 --dataset random-xs-20-angular --run-disabled --timeout 300
```
Seems to complain I don't have docker running.
Do I need to start my own docker daemon before I can run this?

**Comment by thomasahle** [comment]
So adding
```
import sys, os
sys.path.append(os.getcwd() + '/fast_pq')
```
to `ann_benchmarks/algorithms/fast_pq.py` fixed my import errors, but I assume that's not the recommended approach.

**Comment by thomasahle** [comment]
It's that the directory format is
```
fast_pq/
- fast_pq/
  - __init__.py
  - ...
- tests/
- setup.py
- ...
```
The PYTHONPATH should be such that `import fast_pq` imports the module (inner `fast_pq/`), not the outer directory.

**Comment by erikbern** [comment]
Sure, but you don't need that hack if you just install it globally – which would be nice. That's how every other library works right now, and I think it's somewhat cleaner.

**Comment by thomasahle** [comment]
That makes sense. I've updated the build system to work with `pip install .` so everything should be working now.

**Comment by erikbern** [comment]
Awesome. I'll merge this!

**Comment by erikbern** [comment]
Thanks for the contribution!

**Comment by thomasahle** [comment]
Now just fingers crossed that it doesn't suck 🤞

**Pull request merged**
