### PR TITLE
Add PANNG(NGT)

### PR DESCRIPTION
**Pull request by masajiro**
We have added our PANNG of NGT library to the benchmarks.
The PANNG is a combination of a graph-based and tree-based indexes.

### CODE REVIEW

**Comment by erikbern** [comment]
This is great, thanks!

Can you also add it to `.travis.yml`? That way it will run as a part of the unit tests. Thanks!

**Comment by erikbern** [comment]
Actually nvm why don't I just do that myself

**Comment by masajiro** [comment]
Thank you for merging!
Now I do not need to add PANNG to .travis.yml, do I?

**Comment by erikbern** [comment]
No reason to, see https://github.com/erikbern/ann-benchmarks/pull/78

**Pull request merged**
