### PR TITLE
update milvus's version

### PR DESCRIPTION
**Pull request by wangting0128**
update milvus's version 

Signed-off-by: ting.wang@zilliz.com

### CODE REVIEW

**Comment by wangting0128** [comment]
@maumueller

**Comment by maumueller** [comment]
Seems to be working, @wangting0128

**Comment by maumueller** [comment]
Is this ready for merging @wangting0128?

**Comment by wangting0128** [comment]
> Is this ready for merging @wangting0128?

@maumueller yes!

**Comment by maumueller** [comment]
@wangting0128 Sorry, but the last run in CI seems to have failed for milvus. Could you please check?

**Comment by wangting0128** [comment]
> @wangting0128 Sorry, but the last run in CI seems to have failed for milvus. Could you please check?

Please re-run the job of milvus separately, it seems that the problem is caused by the allocated machine @maumueller

**Comment by erikbern** [comment]
Nice, looks like it's passing the tests now!

**Pull request merged**
