### PR TITLE
Upgrade to Ubuntu 20.04 and Python 3.8

### PR DESCRIPTION
**Pull request by alexklibisz**
Upgrade to Ubuntu 20.04 and Python 3.8, re: #316 

Some of the builds are newly-broken. Some were already broken. More detail in #316.

### CODE REVIEW

**Comment by alexklibisz** [comment]
Some of these are still running 3 hours later..

image

**Comment by alexklibisz** [comment]
I also don't see a way to stop the runaway workflow. Even after deleting the branch. Weird.

**Comment by alexklibisz** [comment]
Actually let's maybe wait. I'm testing this out locally with elastiknn and seeing a pretty bad memory leak in the python process, that's causing the container to crash. Maybe it's specific to elastiknn but I need to dig a bit more. The memory leak is definitely in the python process, not the java process, based on just polling `ps` output within the container

**Comment by erikbern** [comment]
That's super strange!

**Comment by alexklibisz** [comment]
Nevermind, I rebased on master and tried again today with Elastiknn and Annoy, and both ran fine. 

I must have messed something up in my local setup. Apologies for the confusion. I cleaned up the commits, so I think we're good to merge here.

**Comment by erikbern** [comment]
Nice! Will merge this assuming most tests are green

**Comment by erikbern** [comment]
A bunch of algorithms are failing with various package/version conflicts right now, but my feeling is that it's not super hard to fix. I'll go through a bunch of them later.

**Comment by erikbern** [comment]
Thanks for this contribution!!

**Pull request merged**
