### PR TITLE
Added PUFFINN

### PR DESCRIPTION
**Pull request by maumueller**
https://github.com/puffinn/puffinn

PUFFINN is an LSH-based ann implementation with support for cosine/jaccard similarity.

Since it doesn't support general Euclidean space, I didn't know what to add to the travis file. (Running it on glove-100-angular would take potentially long.)

### CODE REVIEW

**Comment by erikbern** [comment]
thanks – can you add it to .travis.yml as well so it's tested in CI?

**Comment by maumueller** [comment]
Sure, if you tell me what I should put there.

To quote myself

> Since it doesn't support general Euclidean space, I didn't know what to add to the travis file. (Running it on glove-100-angular would take potentially long.)

**Comment by erikbern** [comment]
ok sorry, i read too fast. the travis tests run random-xs-20-angular so it should be fine.

just add `  - LIBRARY=puffinn DATASET=random-xs-20-angular`

try to keep it sorted lexicographically btw

**Comment by maumueller** [comment]
Oh, right. :-) Thanks. Added it to `.travis.yml`. (And it runs through, two other builds failed.)

**Comment by erikbern** [comment]
sptag is failing, let me check why

**Pull request merged**
