### PR TITLE
Add voyager to algorithms

### PR DESCRIPTION
**Pull request by drubinstein**
Based on hnswlib since voyager is based on it.

CC @psobot @dylanrb123 @markkohdev since they are the primary maintainers of [voyager](https://github.com/spotify/voyager).

### CODE REVIEW

**Comment by erikbern** [comment]
nice!

**Comment by erikbern** [comment]
Thanks!

**Comment by its-mayank** [comment]
Although this PR has been merged week ago, why we can't find voyager on the 
https://ann-benchmarks.com/index.html#algorithms

**Comment by erikbern** [comment]
I need to re-run benchmarks. Will do soon!

**Pull request merged**
