### PR TITLE
Upgrade to Ubuntu 22.04 and Python 3.10

### PR DESCRIPTION
**Pull request by alexklibisz**
Re #316 

* Upgrade the base Docker container to Ubuntu 22.04
* This automatically upgrades Python to 3.10.6
* Upgrade all packages in requirements.txt to their latest versions. I basically just pip-installed them one by one and pegged the requirements file to the version that was installed.

### CODE REVIEW

**Comment by erikbern** [comment]
Nice! Is the plan to do #328 first and then this one? Happy to help out

**Comment by cjnolet** [comment]
It would be nice to see this integrated as Python 3.6 has gotten quite old. I'm working to integrate versions of RAPIDS RAFT ANN algorithms and I have to create a separate conda environment to test the RAPIDS algorithms than for testing algorithms like SCaNN.

**Comment by alexklibisz** [comment]
I'll get this branch cleaned up and ready to merge this week. @erikbern if you haven't started on the fixes for 20.04 yet, it might be best to wait until this branch is merged, so you don't end up doing 2x the work.

**Comment by erikbern** [comment]
ok, sounds good! Would love to merge this soon

**Comment by alexklibisz** [comment]
Ok, I rebased and cleaned up the commits. Ready for a final look and merge when you're ready @erikbern

**Comment by erikbern** [comment]
Awesome, thanks for doing this! I can go through the failures and fix them.

**Pull request merged**
