### PR TITLE
Add support for Faiss

### PR DESCRIPTION
**Pull request by benfred**
This adds basic support for faiss on the cpu as suggested in https://github.com/erikbern/ann-benchmarks/issues/34. The timing results on my system seem to be on par with Annoy on the glove dataset:
glove

### CODE REVIEW

**Comment by erikbern** [comment]
nice! reminds me i really want to dockerize the tests

**Comment by benfred** [comment]
I think that last commit there actually works on travis (was expecting ubuntu v16 originally, and was running on v14). 

Unfortunately there seems to be a bunch of other errors unrelated to this change that will cause the build to be marked as failed. I've fixed the easy ones here https://github.com/benfred/ann-benchmarks/commit/7bf2397effba49216c63b85c7fc4e0de3fd7cc9f and https://github.com/benfred/ann-benchmarks/commit/f6bb17bee32a6e7d752c1a5c533ac077c42b3c7b . However there still seems to be errors on falconn/nearpy.

Also, I wrote some new python bindings for nmslib a while ago, and updated the ann-benchmarks to use them here: https://github.com/benfred/ann-benchmarks/commit/1aec17cb7d676880e371ea3998215d92d533e380 . 

If you're interested I can submit PR's for all of these.

**Comment by erikbern** [comment]
seems fine. i'll merge this for now, will revisit the travis integration and also dockerization

**Comment by erikbern** [comment]
thanks!

**Pull request merged**
