### PR TITLE
Add Elasticsearch KNN

### PR DESCRIPTION
**Pull request by ceh**
Add an implementation for [Elasticsearch KNN search](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html). Fixes https://github.com/erikbern/ann-benchmarks/issues/298.

 - Supports specifying [`index_options`](https://www.elastic.co/guide/en/elasticsearch/reference/8.7/dense-vector.html#dense-vector-params) via arg groups, with one entry for Elasticsearch's [default settings](https://www.elastic.co/guide/en/elasticsearch/reference/8.7/dense-vector.html#dense-vector-params) for M and EF.
 - Supports specifying [`num_candidates`](https://www.elastic.co/guide/en/elasticsearch/reference/8.7/knn-search-api.html#knn-search-api-request-body) via query args.

What do you think @erikbern, @alexklibisz?

### CODE REVIEW

**Comment by ceh** [comment]
Sample run for dataset `fashion-mnist-784-euclidean` on my local machine:

fashion-mnist-784-euclidean

<details>
<summary>Definitions file</summary>
```yaml
float:
  euclidean:
    elasticsearch:
      docker-tag: ann-benchmarks-elasticsearch
      module: ann_benchmarks.algorithms.elasticsearch
      constructor: ElasticsearchKNN
      base-args: ["@metric", "@dimension"]
      run-groups:
        m-16-ef-100:
          arg-groups:
            - {"m": 16,  "ef_construction": 100} # index_options
          query-args: [[10, 20, 30, 40, 50]] # num_candidates
    opensearchknn:
      docker-tag: ann-benchmarks-opensearchknn
      module: ann_benchmarks.algorithms.opensearchknn
      constructor: OpenSearchKNN
      base-args: ["@metric", "@dimension"]
      run-groups:
        M-16:
          arg-groups:
            - {"M": 16,  "efConstruction": 512}
          query-args: [[10, 20, 30, 40, 50]]
```
</details>

**Comment by alexklibisz** [comment]
LGTM, from a very quick skim

**Comment by ceh** [comment]
> want me to merge this right now? i can re-run elasticsearch for the benchmarks (#399)

Nice! Fine to merge! Was thinking about adding a couple of run groups, but takes time to evaluate

**Comment by erikbern** [comment]
i'll probably re-run the benchmarks in the next few weeks anyway

**Pull request merged**
