### PR TITLE
Migrate from Travis to Github Actions

### PR DESCRIPTION
**Pull request by GuilhemN**
Hi,

Since TravisCi for Organizations will shut down in the next few weeks, I thought it would be better to move to Github Actions.

There are a few failures, but I suppose that's similar as when using TravisCI.

What do you think?

### CODE REVIEW

**Comment by erikbern** [comment]
Yeah that sounds like a good idea! I was actually just using Github Actions for the first time last week to set up some stuff so it makes sense. Happy to give it a shot.

**Comment by GuilhemN** [comment]
I think it needs to appear on the default branch to be detected by github and work for later pull requests.

You can check the result the result on my fork meanwhile if you'd like: https://github.com/GuilhemN/ann-benchmarks/actions/runs/819507151

A small note however, Github recently introduced a change that forces to manually trigger CI for first time contributors,  they made an article on that: https://github.blog/changelog/2021-04-22-github-actions-maintainers-must-approve-first-time-contributor-workflow-runs/

**Comment by erikbern** [comment]
let's try merging it and see if it works :)

**Comment by erikbern** [comment]
Looks like it's running: https://github.com/erikbern/ann-benchmarks/actions/runs/840403509

Do you mind updating the README so it points to the Github actions url instead of Travis?

Thanks for doing this!!!!

**Comment by GuilhemN** [comment]
There you go https://github.com/erikbern/ann-benchmarks/pull/236 :smiley:

**Pull request merged**
