### PR TITLE
Fix result caching

### PR DESCRIPTION
**Pull request by sammymax**
Result files end in .hdf5 but the current code neglects this, so it never finds the file, even if the config has already been run.

### CODE REVIEW

**Comment by erikbern** [comment]
This seems related to a refactoring I did a few weeks ago. I don't know if this is the right place to fix it though (ideally it would be fixed in the `get_results_filename` helper). I'll take a look. Thanks for flagging!

**Comment by sammymax** [comment]
No problem, feel free to fix this however you think is best (and disregard/close this PR if needed)!

**Comment by erikbern** [comment]
sorry, dropped the ball, hopefully i can take a look at it this week!

**Comment by maumueller** [comment]
This has been taken care of inside of `get_result_filename` in ae0f175b811f4d95e1f14f4894d2e1eeb5884a3a.

**Pull request closed without merging**
