### PR TITLE
Add Vald to ann-benchmarks

### PR DESCRIPTION
**Pull request by kmrmt**
https://github.com/vdaas/vald

Vald is a highly scalable distributed fast ann search engine.
[NGT](https://github.com/yahoojapan/NGT) is used as the core engine.

### CODE REVIEW

**Review by erikbern — APPROVED** [review]
Nice! Haven't seen Vald

**Comment by savagej** [comment]
You guys have a screenshot from running locally while we wait for this to merge?

**Comment by erikbern** [comment]
Can you add it to https://github.com/erikbern/ann-benchmarks/blob/master/.github/workflows/benchmarks.yml as well so that we get it tested?

**Comment by erikbern** [comment]
Looks like Vald is building, although some other ones are failing. Nice, thanks!

**Pull request merged**
