### PR TITLE
pgvector improvements

### PR DESCRIPTION
**Pull request by ankane**
Initial round of improvements for pgvector:

1. Set `ivfflat.probes` to improve recall
2. Remove `OPTFLAGS=""` so it's compiled with `-march=native` (which enables additional SIMD instructions on supported platforms)
3. Use Unix-domain socket (rather than networking stack)
4. Use binary serialization (to reduce serialization overhead)
5. Use prepared statements (to reduce statement parsing overhead)
6. Increase `work_mem` (to allow for more memory usage)

### CODE REVIEW

**Comment by erikbern** [comment]
Nice! I wasn't able to run it with a unix socket – some permission issue. Did you run into it?

**Comment by erikbern** [comment]
Let me know once this is ready to be merged!

**Comment by ankane** [comment]
Yeah, needed to add the `pg_hba.conf` line to get it working in the Docker image.

It should be in a good spot now to merge.

**Comment by erikbern** [comment]
Thanks! Will rerun in a few days!

**Pull request merged**
