### PR TITLE
Update PyNNDescent

### PR DESCRIPTION
**Pull request by lmcinnes**
Save off indexes when possible to save time, and update the hyper-parameter selections. If I read the file correctly it should choose 'any' for anything unknown, but override with the specific sets for 'euclidean' and 'angular'?

### CODE REVIEW

**Comment by erikbern** [comment]
@maumueller and @ale-f already implemented some kind of index-reusing mechanism in #65 

Let me merge that first, and I think you can use that one as well

**Comment by erikbern** [comment]
@lmcinnes I've merged #65 now – great if you can update your code to use their new approach.

I'm thinking about re-running the benchmarks in the next week or two, so it would be nice to merge this first

**Comment by maumueller** [comment]
Unrelated to this PR: We should also make sure that the graph-based algorithms from nmslib use the new approach. Is there anyone in particular we could ask to do that, Erik?

Also: Can you make sure to store the results of the experiments, Erik? We need to make a journal version of our paper and I’d like to include the newest results.

**Comment by erikbern** [comment]
I think @searchivarius is the right person for nmslib. The "old approach" will work though, it will just be a bit slower.

I can store the results of the experiments. Could potentially just upload them to S3 or something similar.

**Comment by searchivarius** [comment]
@maumueller I am a bit out of context (glossing over the comments didn't help). What's the new approach? Thanks!

**Comment by erikbern** [comment]
@searchivarius sorry for the lack of context. See #65 – ann-benchmarks now supports reusing the datastructure for different query parameters

**Comment by lmcinnes** [comment]
@maumueller I think I read the changes correctly and hopefully this does the right thing. I would definitely appreciate a check from you to ensure I got this correct.

**Comment by erikbern** [comment]
probably works if the unit tests run successfully :)

**Comment by lmcinnes** [comment]
@maumueller Thanks. I think I finally got the last quirks ironed out, so we should be good to go.

**Comment by erikbern** [comment]
Thanks @lmcinnes 

Will run new benchmarks shortly!

**Pull request merged**
