### PR TITLE
Pynndescent

### PR DESCRIPTION
**Pull request by lmcinnes**
Here is a first pass at adding [pynndescent](https://github.com/lmcinnes/pynndescent) to the benchmarks. The implementation is still pretty young, and I'm still working to get a feel for parameter choices, however this should perform adequately, at least for python implementation. I will likely need to update the parameter choice options in algos.yaml in the future to tune things.

### CODE REVIEW

**Comment by erikbern** [comment]
awesome!!!

**Comment by erikbern** [comment]
Can you add pynndescent to `.travis.yml` as well so that it's building in Travis.

**Comment by erikbern** [comment]
Is this ready to be merged? Happy to pull the trigger

**Comment by lmcinnes** [comment]
You can merge it now as long as you would be willing to accept some updates to the `algos.yaml` file at some point in the future.

**Comment by erikbern** [comment]
Thanks @lmcinnes – def feel free to make additional updates in the future!

I'm planning to re-run tests in a couple of weeks, looking forward to include pynndescent

**Comment by lmcinnes** [comment]
Thanks; I look forward to the results.

**Pull request merged**
